cella/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
]

core/urls.py
from django.urls import path
from .views import *

app_name = "core"

urlpatterns=[
    path('', index, name='index'),
    path('login', InicioSeion.as_view(), name='login'),
    path('log_out', cierre, name='log_out'),
    path('join', Registro.as_view(), name='join'),
    path('staff', AdminIndex.as_view(), name='staff'),
]

core/models.py
from django.db import models

class PendingUsers(models.Model):
    UserName    = models.CharField(max_length=30,unique=True)
    password    = models.CharField(max_length=25)
    mail        = models.EmailField(max_length=254, blank=True)

    def __str__(self):
        return self.UserName

core/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth import authenticate, login, logout
from .manager_files import DataManage
from .manage_pending_users import PendingRequest
from django.contrib.auth.models import User
from .models import PendingUsers
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test
import os

def index(request):    
    if (request.user.is_authenticated):
        info = DataManage(request)
        if(request.method=='POST'):

            if request.POST.get('fileDown'):
                ruta = request.POST.get('path')                    
                return info.download(request.POST['fileDown'], ruta)
            
            elif request.POST.get('dirDown'):
                ruta = request.POST.get('path')      
                return info.downloadDir(request.POST['dirDown'], ruta)
            
            elif(request.POST.get('dir')):
                if(request.POST.get('path') == None):
                    context = info.read(request.POST['dir'])
                    return render(request, 'index.html', context)
                else:
                    ruta = os.path.join(request.POST.get('path'),request.POST.get('dir'))
                    context = info.read(ruta)
                    return render(request, 'index.html',context)

            elif(request.POST.get('back')):
                rutaNueva = info.backDir(request.POST['back'])
                context = info.read(rutaNueva)
                return render(request, 'index.html',context) 
               
            elif(request.POST.get('del')):
                nombre = request.POST.get('del')
                tipo = (request.POST.get('type') == 'file')
                if(request.POST.get('path') != None):
                    ruta = request.POST.get('path')
                    info.delete(nombre, tipo, ruta)
                    context = info.read(ruta)
                    return render(request, 'index.html',context)
                else:
                    info.delete(nombre, tipo)
                    context = info.read()
                    return render(request, 'index.html',context)
                
            elif(request.POST.get('nameDir')):
                name = request.POST.get('nameDir')
                ruta = request.POST.get('DirDelPath')
                validacion = info.createDirectory(name,ruta)    
                context = info.read(ruta)
                if(validacion!=None): context['error'] = validacion
                return render(request, 'index.html',context)
            
            elif(request.POST.get('oldName')):
                oldname = request.POST.get('oldName')
                newName = request.POST.get('NewName')
                ruta = request.POST.get('path')
                typeContext = request.POST.get('type')
                extension = request.POST.get('extension')
                validacion = info.rename(typeContext,ruta,oldname,newName,extension)
                context = info.read(ruta)
                if(validacion!=None): context['error'] = validacion
                return render(request, 'index.html', context)
            
            elif(request.FILES.get('fileUp')):
                file = request.FILES['fileUp']
                name = file.name
                ruta = request.POST.get('path')
                info.uploadFile(file, name, ruta, 'file')
                context = info.read(ruta)
                return render(request,'index.html', context)

            elif(request.FILES.get('dirUp')):
                data = request.FILES.getlist('dirUp')
                dataName = request.POST.get('listaArchvios')
                ruta = request.POST.get('path')
                validacion = info.uploadDir(data, dataName, ruta)
                context = info.read(ruta)
                if(validacion!=None): context['error'] = validacion
                return render(request,'index.html',context)
                
            else:
                context = info.read()
                return render(request, 'index.html', context)   
            
        else:
            context=info.read()
            return render(request, 'index.html', context)
            
    else:
        return redirect('/login')


# secion    
class InicioSeion(generic.View):
    tamplate_name = 'login.html'
    user = ''
    password = ''

    def get(self, request):
        if(User.objects.count() == 0):
            return redirect('/join')
        
        if (request.user.is_authenticated):
            return redirect('/')
        return render(request, self.tamplate_name)
    
    def post(self, request):
        if (request.method == "POST"):
            self.user = request.POST['username']
            self.password = request.POST['password']
            check = authenticate(request, username=self.user, password=self.password)
            if check is not None:
                login(request, check)
                return redirect('/') 
            else:
                context={'error':'las contraseñas o usuario no coinsiden'}    
                return render(request, self.tamplate_name,context)


def cierre(request):
    logout(request)
    return redirect('/login')


class Registro(generic.View):
    template_name='join.html'

    def get(self, request):
        if(User.objects.count() == 0):
            return render(request, 'create_super_user.html')
        
        if (request.user.is_authenticated):
            return redirect('/')
        return render(request, self.template_name)
    
    def post(self, request):
        if(User.objects.count() == 0):
            username = request.POST['username']
            password_1 = request.POST['password1']
            password_2 = request.POST['password2']
            email = request.POST['email']   
            if password_1 == password_2:
                User.objects.create_superuser(username=username, email=email, password=password_1)
                check=authenticate(request, username=username, password=password_1)
                if check is not None:
                    login(request, check)
                    return redirect('/')
            else:
                context = {'error':'las contraseñas no coinsiden'}  
                return render(request, 'create_super_user.html', context)
            return render(request, self.template_name, context)        
        else:
            username = request.POST['username']
            password_1 = request.POST['password1']
            password_2 = request.POST['password2']
            email = request.POST['email']
            userRequest = PendingRequest
            context = userRequest.save_panding_user(username, password_1, password_2, email)
            return render(request, self.template_name, context)


def staffCheck(user):
    return user.is_staff


class AdminIndex(generic.View):
    template_name = "admin.html"

    @method_decorator(user_passes_test(staffCheck, login_url='/'))
    def get(self, request):
        context = {'pendingUsers': PendingUsers.objects.all()}
        return render(request, self.template_name,context)
    
    @method_decorator(user_passes_test(staffCheck, login_url='/'))
    def post(self, request):
        pending_users = PendingRequest
        if(request.POST.get('accept')):
            pending_users.accept_user(request.POST['accept'])
        elif(request.POST.get('refuse')):
            pending_users.refuse_user(request.POST['refuse'])
        context = {'pendingUsers': PendingUsers.objects.all()}
        return render(request, self.template_name, context)

templates/admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>staff mode</title>
    <link rel="icon" href="{% static 'icons/logo.svg' %}" type="image/svg+xml">
    <link rel="stylesheet" href="{% static 'css/generics.css' %}">
    <link rel="stylesheet" href="{% static 'css/admin.css' %}">
</head>
<body class="admin-body">
    {% if pendingUsers  %}
        <header class="header-admin">
            <h1>Staff zone</h1>
            <a class="button-dark-mode generic-padding-button" href="{% url 'core:index' %}">volver</a>
        </header>
        <table >
            
            <tbody>
                <tr style="padding-bottom: 1.2em;">
                    <th>
                        <p>
                            usarios
                        </p>
                    </th>
                    <th>
                        aciones
                    </th>
                </tr>
                {% for i in pendingUsers %}
                    <tr class="column-hover " >
                        <th class="conteiner-center">
                            <p class="usernames">{{i}}</p>
                        </th>
                        <th>
                            <form method="post" class="coneiner-buttons-actions">
                                {% csrf_token %}
                                <button class="button-refuse generic-padding-button" name='refuse' value="{{i}}" type="submit">Rechazar</button>    
                                <button class="button-accept generic-padding-button" name='accept' value="{{i}}" type="submit">Aceptar</button>
                            </form>
                    
                        </th>
                    </tr>
                {% endfor %}    
            </tbody>
        </table>
    {% else %}
        <div class="conteiner-no-users-request">
            <h1 class=""> No hay solicitudes </h1>
            <a class="button-dark-mode generic-padding-button"  href="{% url 'core:index' %}">volver</a>
        </div>
    {% endif %}
    <footer class="footer-admin">
        <a class="button-dark-mode generic-padding-button" href="{% url 'core:index' %}">volver</a>

    </footer>
</body>
</html>

templates/crateSuperuser.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>join</title>
        <link rel="stylesheet" href="{% static 'estilos.css' %}">
        <style>
            @font-face{
                font-family: 'AgaveNerdFontMono-Regular';
                src: url("{% static 'fuente/AgaveNerdFontMono-Regular.ttf' %}") format('truetype');
            }
            body{
                font-family: 'AgaveNerdFontMono-Regular';
            }
            
        </style>
    </head>
    <body style='background-color: rgb(48, 28, 42); display: flex; align-items: center; justify-content: center;'>
        {% if message %}
        <dialog open id="message_join_dialog">
            {{ message }}
            <button onclick="window.message_join_dialog.close()">cerrar</button>
        </dialog>
    {% endif %}
        <h1>Bienvenido a cella</h1>
        <div style=" background-color: rgb(70, 27, 54); width: 30%; box-shadow: 5px 5px;display: flex; border-radius: 0.2em; align-items: center; justify-content: center; min-width: 288px; max-width: 288px;">
            
                <form method="post" class="loginForm" >
                    {% csrf_token %}
                    <label class="loginTexto" >Usuario</label>
                    <input class="loginInput" type="text" required name="username">
        
                    <label class="loginTexto">contraseña</label>
                    <div >
                        <input style="padding: 1em;" type="checkbox" name="" id="MostrarPass1">
                        <input class="loginInput" type="password" required name="password1" id="passW1">
                    </div>
                        <label class="loginTexto">de nuevo contraseña</label>
                
                    <div>
                        <input style="padding: 1em;" type="checkbox" name="" id="MostrarPass2">
                        <input class="loginInput" type="password" required name="password2" id="passW2">    
                    </div>
                    <label class="loginTexto" >Correo</label>
                    <input class="loginInput" type="email" required name="email">

                    <button class="loginButton" type="submit">Crear</button>
                </form>
>

                <script>
                    const check1= document.getElementById('MostrarPass1')
                    check1.addEventListener('click',()=>{visibilidad(document.getElementById('passW1'))})
                    const check2= document.getElementById('MostrarPass2')
                    check2.addEventListener('click',()=>{visibilidad(document.getElementById('passW2'))})
                    function visibilidad(pass){
                        if(pass.type=='text'){
                            pass.type='password'
                        }else{
                            pass.type='text'
                        }
                    }
                </script>
        </div>

    </body>
</html>

templates/create_super_user.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>join</title>
        <link rel="icon" href="{% static 'icons/logo.svg' %}" type="image/svg+xml">
        <link rel="stylesheet" href="{% static 'css/session.css' %}">
        <link rel="stylesheet" href="{% static 'css/generics.css' %}">
    </head>
    <body >
        {% if error  %}
            <dialog  id="errorCella" class='error-mesagge'>
                <center>
                    <p>{{ error }}</p>
                    <button class='button-error' onclick="window.errorCella.close()"> cerrar</button>     
                </center>
            </dialog>
            <script>
                window.errorCella.showModal();
            </script>
        {% endif %}
        <div class="container-session">
                <div class="create-first-account">
                    <h1 style="font-family: monospace;">Bienvenido</h1>
                    <img style="width: 60px;" src="{% static 'icons/logo.svg' %}" alt="cella-icon">
                </div>    
                <form method="post" class="session-form" >
                    {% csrf_token %}
                    <label class="session-label-text" >Usuario</label>
                    <input class="text-input input-space" type="text" required name="username">
        
                    <label class="session-label-text">contraseña</label>
                    <div class="container-password input-space">
                        <input class="check-password" type="checkbox" name="" id="MostrarPass1">
                        <input class="text-input" type="password" required name="password1" id="passW1">
                    </div>
                        <label class="session-label-text">de nuevo contraseña</label>
                    <div class="container-password input-space">
                        <input class="check-password" type="checkbox" name="" id="MostrarPass2">
                        <input class="text-input" type="password" required name="password2" id="passW2">    
                    </div>
                    <label class="session-label-text" >Correo</label>
                    <input class="text-input input-space" type="email" required name="email">

                    <button class="button-dark-mode button-session" type="submit">Crear</button>
                </form>
                <script>
                    const check1= document.getElementById('MostrarPass1')
                    check1.addEventListener('click',()=>{visibilidad(document.getElementById('passW1'))})
                    const check2= document.getElementById('MostrarPass2')
                    check2.addEventListener('click',()=>{visibilidad(document.getElementById('passW2'))})
                    function visibilidad(pass){
                        if(pass.type=='text'){
                            pass.type='password'
                        }else{
                            pass.type='text'
                        }
                    }
                </script>
        </div>

    </body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>CELLA</title>
        <link rel="icon" href="{% static 'icons/logo.svg' %}" type="image/svg+xml">
        <link rel="stylesheet" href="{% static 'css/generics.css' %}">
        <link rel="stylesheet" href="{% static 'css/index.css' %}">
        <script src="{% static 'funcionalidad.js' %}"></script>
    </head>
    <body>
        <header>
            <div onclick="menuResponsive()" class="button-cella-dark">
                <span style="padding-top:4.2em; min-height: 3.5rem; min-width: 3.5rem; background-image:url({% static 'icons/logo.svg' %}); background-repeat:no-repeat; ">
                <h2 style='color:rgb(35, 17, 37)'>CELLA</h2>
            </div>
            <div class="header-buttons-grup">
                <button onclick="window.CrearCarpertaFormulario.showModal()" class="button-dark-mode header-buttons"> crear carpeta</button>
                <button onclick="window.subirMenuFile.showModal();" class="button-dark-mode header-buttons">Subir archivo</button>
                <button onclick="window.subirMenuDir.showModal();" class="button-dark-mode header-buttons">Subir carpeta</button>
                {% if user.is_staff %}
                <a class='button-dark-mode header-buttons' href="{% url 'core:staff' %}">modo staff</a>
                {% endif %}
            </div>                
        </header>
        <!-- dialogs menu --> 
        <dialog id="CrearCarpertaFormulario" class='dialogs-actions'>
            <form method="post">
                {% csrf_token %}
                <label class="dialogs-names-labels" >Nombre de la carpeta:</label>
                <br>                
                <input type="hidden" name="DirDelPath" value="{{ ruta }}">
                <input required maxlength="80" class='text-input' type="text" name="nameDir">
                <div class='conteiner-between'>
                    <button class='button-dark-mode dialogs-buttons'type="button" onclick="window.CrearCarpertaFormulario.close()"> cerrar</button>
                    <button class='button-dark-mode dialogs-buttons' type="submit" name="meakedir"> crear </button>
                </div>
            </form>
        </dialog>
        <dialog id="subirMenuDir" class='dialogs-actions'>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input name="path" type='hidden' value="{{ ruta }}">
                <div class="button-dark-mode"  >
                    <input onchange="FundirUp()" id="dirUp" name="dirUp" type="file" webkitdirectory directory multiple>
                </div>
                <div id="listDataArchivos" ></div>
                <div class='conteiner-between'>
                    <button class='button-dark-mode dialogs-buttons' type="button" onclick="window.subirMenuDir.close();">cerrar</button>
                    <button class='button-dark-mode dialogs-buttons' type="submit">enviar</button>
                </div>
            </form>
        </dialog>
        <dialog id="subirMenuFile" class='dialogs-actions'>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input name="path" type='hidden' value="{{ ruta }}">
                <div class="button-dark-mode">
                    <input name="fileUp" type="file">
                </div>
                <div class='conteiner-between'>
                    <button class='button-dark-mode dialogs-buttons' type="button" onclick="window.subirMenuFile.close();">cerrar</button>
                    <button class='button-dark-mode dialogs-buttons' type="submit">enviar</button>
                </div>
            </form>
        </dialog>   
        <dialog id="renombrarMenu" class='dialogs-actions'>
            <form  method="post">
                {% csrf_token %}
                <input name="path" type='hidden' value="{{ ruta }}">
                <label class="dialogs-names-labels" >Nuevo nombre:</label>
                <br>
                <input class='text-input' name="NewName" maxlength="80" required type="text">
                <div id="renombrarContext"></div>
                <div class='conteiner-between'>
                    <button class='button-dark-mode dialogs-buttons' type="submit" name='rename' >confimar</button>
                    <button class='button-dark-mode dialogs-buttons' type="button" onclick="window.renombrarMenu.close()">cerrar</button>
                </div>    
            </form>
        </dialog>
<!-- error message --> 
        {% if error  %}
            <dialog  id="errorCella" class='error-mesagge'>
                <center>
                    <p>{{ error }}</p>
                    <button class='button-error' onclick="window.errorCella.close()"> cerrar</button>     
                </center>
            </dialog>
            <script>
                window.errorCella.showModal();
            </script>
        {% endif %}
        <main>
<!-- menu full screen --> 
            <span id="menuResponsiveID">
                <svg onclick="menuResponsive()" class='menu-phone-cancel' style='margin:2em' xmlns="http://www.w3.org/2000/svg" width="55" height="55" viewBox="0 0 24 24"><path fill="currentColor" d="m12 13.4l2.9 2.9q.275.275.7.275t.7-.275t.275-.7t-.275-.7L13.4 12l2.9-2.9q.275-.275.275-.7t-.275-.7t-.7-.275t-.7.275L12 10.6L9.1 7.7q-.275-.275-.7-.275t-.7.275t-.275.7t.275.7l2.9 2.9l-2.9 2.9q-.275.275-.275.7t.275.7t.7.275t.7-.275zm0 8.6q-2.075 0-3.9-.788t-3.175-2.137T2.788 15.9T2 12t.788-3.9t2.137-3.175T8.1 2.788T12 2t3.9.788t3.175 2.137T21.213 8.1T22 12t-.788 3.9t-2.137 3.175t-3.175 2.138T12 22m0-2q3.35 0 5.675-2.325T20 12t-2.325-5.675T12 4T6.325 6.325T4 12t2.325 5.675T12 20m0-8"/></svg>
                <div class='menu-renameesponsive-buttons'>    
                    <button onclick="window.CrearCarpertaFormulario.showModal()" class="button-dark-mode menu-responsive-buttons"> crear carpeta</button>
                    <button onclick="window.subirMenuFile.showModal();" class="button-dark-mode menu-responsive-buttons">Subir archivo</button>
                    <button onclick="window.subirMenuDir.showModal();" class="button-dark-mode menu-responsive-buttons">Subir carpeta</button>
                    {% if user.is_staff %}
                    <a class='button-dark-mode menu-responsive-buttons' href="{% url 'core:staff' %}">modo staff</a>
                    {% endif %}
                    <a class='button-dark-mode menu-responsive-buttons' href="{% url 'core:log_out' %}">Cerrar sesión</a>
                </div>    
            </span>
<!-- user path --> 
            {% if ruta %}
                <div class='conteiner-between user-path-conteiner'>
                    <form method="post" >
                        {% csrf_token %}
                        <button class="button-icons"  name="back" value="{{ ruta }}"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M6.325 12.85q-.225-.15-.337-.375T5.874 12t.113-.475t.337-.375l8.15-5.175q.125-.075.263-.112T15 5.825q.4 0 .7.288t.3.712v10.35q0 .425-.3.713t-.7.287q-.125 0-.262-.038t-.263-.112z"/></svg></button>
                    </form>
                    <p class="user-path-text" >Inicio/{{ ruta }}</p>
                    <form method="post" >
                        {% csrf_token %}
                            <button class="button-icons" ><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M4 19v-9q0-.475.213-.9t.587-.7l6-4.5q.525-.4 1.2-.4t1.2.4l6 4.5q.375.275.588.7T20 10v9q0 .825-.588 1.413T18 21h-3q-.425 0-.712-.288T14 20v-5q0-.425-.288-.712T13 14h-2q-.425 0-.712.288T10 15v5q0 .425-.288.713T9 21H6q-.825 0-1.412-.587T4 19"/></svg></button>
                    </form>
                </div>

            {% else %}
                <div class='conteiner-center user-path-conteiner'>
                    <center>
                        <p class="user-path-text">Inicio</p>
                    </center> 
                </div> 
            {% endif %}
<!-- content --> 
                {% if not carpetas and not archivos %}
                    <div class='conteiner-center' style='height:100%;'>
                        <h2 style='color:white'>No hay documento guardados :c</h2>
                    </div>
                {% endif %}
<!-- content directories --> 
                {% if carpetas %}
                    <h2 class='titles-content'>Carpetas</h2>
                    {% for i in carpetas%}
                        <form class="form-buttons" method="post">
                            {% csrf_token %}
                            {% if ruta %}
                                <input name="path" type='hidden' value="{{ ruta }}">
                            {% endif %}
                            <div class='conteiner-buttons'>
                                <button class="user-directories-names" name="dir" value="{{ i }}" >{{ i }}</button>
                                <div class='subcontainer-buttons'>
                                    <button class="button-icons" type="submit" name='dirDown' value="{{  i }}"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M4 22v-2h16v2zm8-4L5 9h4V2h6v7h4z"/></svg></button>    
                                    <button class="button-icons" type="button" onclick="rename('{{i}}','dir'); "><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M2 24v-4h20v4zm2-6v-4.25L15.2 2.575q.275-.275.638-.425T16.6 2t.775.15t.675.45L19.425 4q.3.275.438.65t.137.775q0 .375-.137.738t-.438.662L8.25 18zM16.6 6.8L18 5.4L16.6 4l-1.4 1.4z"/></svg></button>
                                    <button class="button-icons" type="submit" name='del' value="{{  i }}"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M7 21q-.825 0-1.412-.587T5 19V6H4V4h5V3h6v1h5v2h-1v13q0 .825-.587 1.413T17 21zm2-4h2V8H9zm4 0h2V8h-2z"/></svg></button>            
                                </div>
                            </div>
                        </form>
                    {% endfor %}
                {% endif %}
<!-- content files --> 
                {% if archivos %}
                    <h2 class='titles-content' style='margin-top: .8em;'>Archivos</h2>
                    {% for i in archivos%}
                        <form class="form-buttons select-file" method="post">
                            {% csrf_token %}           
                            <div class='conteiner-buttons'>
                                <p class='title-file'> {{ i }} </p>
                                <div class='subcontainer-buttons'>
                                    <input name="type" type='hidden' value='file'>
                                    <input name="path" type='hidden' value="{{ ruta }}">
                                    <button class="button-icons" type="submit" name='fileDown' value="{{  i }}"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M4 22v-2h16v2zm8-4L5 9h4V2h6v7h4z"/></svg></button>    
                                    <button class="button-icons" type="button" onclick="rename('{{i}}','file'); "><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M2 24v-4h20v4zm2-6v-4.25L15.2 2.575q.275-.275.638-.425T16.6 2t.775.15t.675.45L19.425 4q.3.275.438.65t.137.775q0 .375-.137.738t-.438.662L8.25 18zM16.6 6.8L18 5.4L16.6 4l-1.4 1.4z"/></svg></button>  
                                    <button class="button-icons" type="submit" name='del' value="{{  i }}"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M7 21q-.825 0-1.412-.587T5 19V6H4V4h5V3h6v1h5v2h-1v13q0 .825-.587 1.413T17 21zm2-4h2V8H9zm4 0h2V8h-2z"/></svg></button>  
                                </div>
                            </div>
                        </form>
                    {% endfor %}
                {% endif %}
        </main>
        <footer >
            <a class='button-dark-mode button-footer' href="{% url 'core:log_out' %}">Cerrar</a>
        </footer> 
    </body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Inicio sesion</title>
        <link rel="icon" href="{% static 'icons/logo.svg' %}" type="image/svg+xml">
        <link rel="stylesheet" href="{% static 'css/generics.css' %}">
        <link rel="stylesheet" href="{% static 'css/session.css' %}">
    </head>
    <body>
        {% if error  %}
        <dialog  id="errorCella" class='error-mesagge'>
            <center>
                <p>{{ error }}</p>
                <button class='button-error' onclick="window.errorCella.close()"> cerrar</button>     
            </center>
        </dialog>
        <script>
            window.errorCella.showModal();
        </script>
        {% endif %}
        <div class="container-session">
                <form method="post" class="session-form" >
                    {% csrf_token %}
                    <label class="session-label-text" >Usuario</label>
                    <input class="text-input input-space"  type="text" required name="username">
                    <label class="session-label-text">contraseña</label>
                    <input class="text-input input-space" type="password" required name="password" id="">
                        <button class="button-dark-mode button-session" type="submit">Acceder</button>
                        <a  class="button-dark-mode button-session" href='./join'>Solicitar una cuenta</a>
                </form>
        </div>
    </body>
</html>